version: "3"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  docs:
    image:  squidfunk/mkdocs-material
    volumes:
      - ./docs:/docs
    environment:
      VIRTUAL_HOST: docs.localtest.me

  dashboard:
    image: moveyourfeet/dashboard
    build:
      context: "./dashboard"
    ports:
      - "8000:80"
    environment:
      VIRTUAL_HOST: dashboard.localtest.me

  mobilebff:
    build:
      context: "./mobileBFF"
    environment:
      VIRTUAL_HOST: mobilebff.localtest.me
      VIRTUAL_PORT: 80
      PORT: 80
    ports:
      - "8003:80"

  nats:
    image: 'nats:0.8.0'
    entrypoint: "/gnatsd -DV" # -D debug, -V Trace the raw protocol
    hostname: nats-server
    ports:
      - "4222:4222"

  tester:
    build:
      context: "./tester"
    environment:
      - "NATS_URI=nats://nats:4222"
    ports:
      - "8080:8080"

  recentlocations:
    image: moveyourfeet/recentlocations
    build:
      context: "./recentLocations"
    environment:
      NATS_URI: nats://nats:4222
      VIRTUAL_HOST: recentlocations.localtest.me
      PORT: 80
    ports:
      - "8002:80"

  gamemanager-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"

  gamemanager:
    image: moveyourfeet/gamemanager
    build:
      context: "./gameManager"
    restart: always
    ports:
      - "8001:80"
    environment:
      ENVIRONMENT: "Development"
      PORT: 80
      DB_HOST: "gamemanager-db"
      DB_NAME: "postgres"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "mypass"
      DB_PORT: 5432
      JWT_SECRET: "A super secret password"
      VIRTUAL_HOST: gamemanager.localtest.me
