basePath: '{{.BasePath}}'
definitions:
  http.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: boolean
      message:
        type: string
    type: object
  http.Health:
    properties:
      status:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /healthz:
    get:
      description: Service Health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Health'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ErrorResponse'
            type: object
      summary: Service Health
      tags:
      - System
  /locations/{gameId}:
    get:
      consumes:
      - application/json
      description: Get player locations for a game
      parameters:
      - description: Game ID
        in: path
        name: gameId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interface'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ErrorResponse'
            type: object
      summary: Get player locations for a game
      tags:
      - Locations
swagger: "2.0"
